language: c
before_script: developers/install-poly.sh
script: $SML < tools/smart-configure.sml && bin/build $BUILDOPTS --nograph
notifications:
  email:
    on_success: always
    on_failure: always

env:
  global:
    - PATH=$PATH:$HOME/bin LD_LIBRARY_PATH=$HOME/lib
  matrix:
    - SML=mosml BUILDOPTS="--seq=developers/travis/smallseq"
    - SML=mosml BUILDOPTS="--seq=tools/sequences/kernel -t1"
    - SML=poly BUILDOPTS="--seq=developers/travis/smallseq"
    - SML=poly BUILDOPTS="--seq=developers/travis/smallseq --expk"
    - SML=poly BUILDOPTS="--seq=developers/travis/smallseq -t1"
    - SML=poly BUILDOPTS="--expk --seq=developers/travis/smallseq -t1"
    - SML=poly BUILDOPTS="--seq=developers/travis/smallseq -t1"
    - SML=poly BUILDOPTS="--expk --seq=developers/travis/smallseq -t1"
    - SML=poly POLY_GIT=T BUILDOPTS="--seq=developers/travis/smallseq"
    - SML=poly POLY_INTINF="--enable-intinf-as-int --seq=developers/travis/smallseq"
matrix:
  include:
    - os: osx
      env: SML=poly BUILDOPTS=
    - env: SML=poly POLY_ROOT=T BUILDOPTS="--seq developers/travis/smallseq"
      sudo: true
    - env: SML=poly OPENTHEORY=T BUILDOPTS="--otknl --seq developers/travis/vsmallseq"
  allow_failures:
    - os: osx
    - env: SML=poly POLY_GIT=T BUILDOPTS="--seq=developers/travis/smallseq"
